/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.life;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void app_DoitAvoirUneInstanceDe_Game() {
        assertDoesNotThrow(() -> App.class.getDeclaredField("game"));
    }

    @Test
    void game_DoitEtreDeType_Game() throws NoSuchFieldException, SecurityException {
        assertEquals(Game.class.getClass(), App.class.getDeclaredField("game").getType().getClass());
    }
}
