/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.life;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

class GameTest {
    @Test
    void neDoitPas_AvoirDeConstructeurPublic() {
        assertThrows(Exception.class, () -> Game.class.getConstructor());
    }

    @Test
    void doit_AvoirUneMethode_getInstance() {
        assertDoesNotThrow(() -> Game.class.getDeclaredMethod("getInstance"));
    }

    @Test
    void getInstance_DoitRetournerUneInstance_Game() throws NoSuchMethodException, SecurityException {
        assertEquals(Game.class.getClass(), Game.class.getDeclaredMethod("getInstance").getReturnType().getClass());
    }
}
