#!/bin/bash

# Développeur ....: K3rn€l_P4n1K
# Nom ............: zsh
# Description ....: Configuration personnelle de zsh
# Version ........: 1.0
# Date ...........: Fri Jul 29 21:31:48 CEST 2022
# Dépendances ....: zsh
alias vim='nvim'
alias v='nvim'
alias v.v='v .vimrc'

# edition des dotfiles
alias rc='~/.dotfiles/install'
alias sz='source ~/.zshrc'

alias l.va='lynx http://github.com/amix/vimrc -dump'
alias vv='v ~/.dotfiles/conf/vim'
alias vvrc='cd ~/.vim_runtime/vimrcs; v; cd -'
alias cvrc='cd ~/.vim_runtime/vimrcs'
alias cn='cd ~/.config/nvim'
alias vn='v ~/.dotfiles/conf/nvim.lua'
alias vz='v ~/.dotfiles/conf/zsh; sz'
alias vc='v ~/.dotfiles/install.conf.yaml'
alias c.='cd ~/.dotfiles'
alias v.='c.; v; cd -'
alias c.va='cat ~/.dotfiles/install.conf.yaml | egrep "vim-awesome.*install" | sed "s/^\s*-\s\(\S\+\|-\)\s\S\+//" | tr -d " " | egrep -v "^$"'
alias al='cat ~/.dotfiles/conf/zsh | grep alias | column -t -s = | sort'
alias mcp='mvn clean package | fzf -m --tac'
alias mcpd='mvn clean package -Dmaven.surefire.debug | fzf -m --tac'


function c.va.td(){
    installed=`mktemp`
    wanted=`mktemp`
    vim-awesome search -i | sort | uniq > ${installed}
    c.va | sort | uniq > ${wanted}
    comm -3 ${installed} ${wanted}
}
alias c.va.DEL='c.va.td | xargs -n1 vim-awesome uninstall'

# configuration du clavier
alias k='chrysalis'

# node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# docker
alias docker.arrete_tous_les_containers='docker container stop $(docker container ls -aq)'
alias docker.supprime_tous_les_containers='docker container rm $(docker container ls -q)'
alias docker.supprime_toutes_les_images='docker image rm $(docker image ls -q)'

alias docker.NETTOIE_TOUT='docker.arrete_tous_les_containers; docker.supprime_tous_les_containers; docker.supprime_toutes_les_images'

# atuin
installe_atuin(){
    # do not run this as root, root will be asked for if required
    bash <(curl https://raw.githubusercontent.com/ellie/atuin/main/install.sh)
    echo 'eval "$(atuin init zsh)"' >> ~/.zshrc
}
docker.status(){ # TODO: faire un script avec bash simple curses 
    echo
    echo "volumes"
    docker volume ls
    echo
    echo "images"
    docker image ls
    echo
    echo "containers"
    docker container ls
}
# chrysalis
installe_chrysalis(){
    wget  https://github.com/keyboardio/Chrysalis/releases/download/v0.11.0/Chrysalis-0.11.0.AppImage -O ~/bin/chrysalis
    chmod +x ~/bin/chrysalis
}
# sdkman
[[ -s "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${HOME}/.sdkman/bin/sdkman-init.sh"

PATH="$HOME/bin:$PATH"


#ZSH_THEME=3den
#ZSH_THEME=Soliah
#ZSH_THEME=adben
#ZSH_THEME=af-magic
#ZSH_THEME=afowler
#ZSH_THEME=agnoster
#ZSH_THEME=alanpeabody
#ZSH_THEME=amuse
#ZSH_THEME=apple
#ZSH_THEME=arrow
#ZSH_THEME=aussiegeek
#ZSH_THEME=avit
#ZSH_THEME=awesomepanda
#ZSH_THEME=bira
#ZSH_THEME=blinks
#ZSH_THEME=bureau
#ZSH_THEME=candy-kingdom
#ZSH_THEME=candy
#ZSH_THEME=clean
#ZSH_THEME=cloud
#ZSH_THEME=crcandy
#ZSH_THEME=crunch
#ZSH_THEME=cypher
#ZSH_THEME=dallas
#ZSH_THEME=darkblood
#ZSH_THEME=daveverwer
#ZSH_THEME=dieter
#ZSH_THEME=dogenpunk
#ZSH_THEME=dpoggi
#ZSH_THEME=dst
#ZSH_THEME=dstufft
#ZSH_THEME=duellj
#ZSH_THEME=eastwood
#ZSH_THEME=edvardm
#ZSH_THEME=emotty
#ZSH_THEME=essembeh
#ZSH_THEME=evan
#ZSH_THEME=fino-time
#ZSH_THEME=fino
#ZSH_THEME=fishy
#ZSH_THEME=flazz
#ZSH_THEME=fletcherm
#ZSH_THEME=fox
#ZSH_THEME=frisk
#ZSH_THEME=frontcube
#ZSH_THEME=funky
#ZSH_THEME=fwalch
#ZSH_THEME=gallifrey
#ZSH_THEME=gallois
#ZSH_THEME=garyblessington
#ZSH_THEME=gentoo
#ZSH_THEME=geoffgarside
#ZSH_THEME=gianu
#ZSH_THEME=gnzh
#ZSH_THEME=gozilla
#ZSH_THEME=half-life
#ZSH_THEME=humza
#ZSH_THEME=imajes
#ZSH_THEME=intheloop
#ZSH_THEME=itchy
#ZSH_THEME=jaischeema
#ZSH_THEME=jbergantine
#ZSH_THEME=jispwoso
#ZSH_THEME=jnrowe
#ZSH_THEME=jonathan
#ZSH_THEME=josh
#ZSH_THEME=jreese
#ZSH_THEME=jtriley
#ZSH_THEME=juanghurtado
#ZSH_THEME=junkfood
#ZSH_THEME=kafeitu
#ZSH_THEME=kardan
#ZSH_THEME=kennethreitz
#ZSH_THEME=kiwi
#ZSH_THEME=kolo
#ZSH_THEME=kphoen
#ZSH_THEME=lambda
#ZSH_THEME=linuxonly
#ZSH_THEME=lukerandall
#ZSH_THEME=macovsky-ruby
#ZSH_THEME=macovsky
#ZSH_THEME=maran
#ZSH_THEME=mgutz
#ZSH_THEME=mh
#ZSH_THEME=michelebologna
#ZSH_THEME=mikeh
#ZSH_THEME=miloshadzic
#ZSH_THEME=minimal
#ZSH_THEME=mira
#ZSH_THEME=mlh
#ZSH_THEME=mortalscumbag
#ZSH_THEME=mrtazz
#ZSH_THEME=murilasso
#ZSH_THEME=muse
#ZSH_THEME=nanotech
#ZSH_THEME=nebirhos
#ZSH_THEME=nicoulaj
#ZSH_THEME=norm
#ZSH_THEME=obraun
#ZSH_THEME=peepcode
#ZSH_THEME=philips
#ZSH_THEME=pmcgee
#ZSH_THEME=pygmalion-virtualenv
#ZSH_THEME=pygmalion
#ZSH_THEME=random
#ZSH_THEME=re5et
#ZSH_THEME=refined
#ZSH_THEME=rgm
#ZSH_THEME=risto
#ZSH_THEME=rixius
#ZSH_THEME=rkj-repos
#ZSH_THEME=rkj
#ZSH_THEME=robbyrussell
#ZSH_THEME=sammy
#ZSH_THEME=simonoff
#ZSH_THEME=simple
#ZSH_THEME=skaro
#ZSH_THEME=smt
#ZSH_THEME=sonicradish
#ZSH_THEME=sorin
#ZSH_THEME=sporty_256
#ZSH_THEME=steeef
#ZSH_THEME=strug
#ZSH_THEME=sunaku
#ZSH_THEME=sunrise
#ZSH_THEME=superjarin
#ZSH_THEME=suvash
#ZSH_THEME=takashiyoshida
#ZSH_THEME=terminalparty
#ZSH_THEME=theunraveler
#ZSH_THEME=tjkirch
#ZSH_THEME=tjkirch_mod
#ZSH_THEME=tonotdo
#ZSH_THEME=trapd00r
#ZSH_THEME=wedisagree
#ZSH_THEME=wezm+
#ZSH_THEME=wezm
#ZSH_THEME=wuffers
#ZSH_THEME=xiong-chiamiov-plus
#ZSH_THEME=xiong-chiamiov
#ZSH_THEME=ys
ZSH_THEME=zhann
