/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package builder;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

import org.junit.jupiter.api.Test;

class BoyBuilderTest {

    @Test
    void doit_AvoirUnBuilderPour_balance() throws SecurityException, NoSuchMethodException {
        assertDoesNotThrow(() -> BoyBuilder.class.getDeclaredMethod("buildBalance"));
    }

    @Test
    void doiAvoirUnBuilderPour_picture() {
        assertDoesNotThrow(() -> BoyBuilder.class.getDeclaredMethod("buildPicture"));
    }

    @Test
    void doiAvoirUnBuilderPour_age() {
        assertDoesNotThrow(() -> BoyBuilder.class.getDeclaredMethod("buildAge"));
    }

    @Test
    void doiAvoirUnBuilderPour_name() {
        assertDoesNotThrow(() -> BoyBuilder.class.getDeclaredMethod("buildName"));
    }

    @Test
    void doiAvoirUnBuilderPour_gender() {
        assertDoesNotThrow(() -> BoyBuilder.class.getDeclaredMethod("buildGender"));
    }

    @Test
    void doiAvoirUnBuilderPour_company() {
        assertDoesNotThrow(() -> BoyBuilder.class.getDeclaredMethod("buildCompany"));
    }

    @Test
    void doiAvoirUnBuilderPour_email() {
        assertDoesNotThrow(() -> BoyBuilder.class.getDeclaredMethod("buildEmail"));
    }
}