/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package builder;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.lang.reflect.Method;

import org.junit.jupiter.api.Test;

class UserBuilderTest {

    @Test
    void doit_AvoirUneMethodePourRecuperer_User() throws NoSuchMethodException, SecurityException {
        Method declaredMethod = UserBuilder.class.getDeclaredMethod("get");
        assertEquals(declaredMethod.getReturnType().toString(), "class builder.User");
    }

    @Test
    void doit_AvoirUneMethodePourRecupererUnUtilisateur() {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("get"));
    }

    @Test
    void doit_AvoirUneMethodePourCreerUn_User() throws SecurityException, NoSuchMethodException {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("build"));
    }

    @Test
    void doit_AvoirUnBuilderPour_balance() throws SecurityException, NoSuchMethodException {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("buildBalance"));
    }

    @Test
    void doiAvoirUnBuilderPour_picture() {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("buildPicture"));
    }

    @Test
    void doiAvoirUnBuilderPour_age() {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("buildAge"));
    }

    @Test
    void doiAvoirUnBuilderPour_name() {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("buildName"));
    }

    @Test
    void doiAvoirUnBuilderPour_gender() {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("buildGender"));
    }

    @Test
    void doiAvoirUnBuilderPour_company() {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("buildCompany"));
    }

    @Test
    void doiAvoirUnBuilderPour_email() {
        assertDoesNotThrow(() -> UserBuilder.class.getDeclaredMethod("buildEmail"));
    }
}