/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package patterns.abstractfactory;


import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import patterns.abstractfactory.fabrique.Fenetre;
import patterns.abstractfactory.fabrique.ScrollBar;
import patterns.abstractfactory.fabrique.WidgetFabrique;
import patterns.abstractfactory.fabrique.b.FenetreB;
import patterns.abstractfactory.fabrique.b.ScrollBarB;
import patterns.abstractfactory.fabrique.b.WidgetFabriqueB;

class WidgetFabriqueBTest {
    private WidgetFabriqueB fabriqueB = new WidgetFabriqueB();
    
    @Test void doit_EtreDeTypeWidgetFabrique(){
        assertTrue(fabriqueB instanceof WidgetFabrique );
    }

    @Test void doit_AvoirUneMethodePourCreerDesScrollbars(){
        assertNotNull(fabriqueB.fabriqueScrollBar());
    }
    
    @Test void fabriqueScrollbar_doit_RetournerDesScrollbarsDeTypeA(){
        assertTrue(fabriqueB.fabriqueScrollBar() instanceof ScrollBarB);
    }

    @Test void fabriqueScrollbar_doit_RetournerDesScrollbars(){
        assertTrue(fabriqueB.fabriqueScrollBar() instanceof ScrollBar);
    }
    
    @Test void fabriqueFenetre_doit_AvoirUneMethodePourCreerDesFenetres(){
        assertNotNull(fabriqueB.fabriqueFenetre());
    }
    
    @Test void fabriqueFenetre_doit_RetournerUneFenetreDeTypeA(){
        assertTrue(fabriqueB.fabriqueFenetre() instanceof FenetreB);
    }
    
    @Test void fabriqueFenetre_doit_RetournerUneFenetre(){
        assertTrue(fabriqueB.fabriqueFenetre() instanceof Fenetre);
    }
}
