/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package patterns.abstractfactory;


import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import patterns.abstractfactory.fabrique.Fenetre;
import patterns.abstractfactory.fabrique.ScrollBar;
import patterns.abstractfactory.fabrique.WidgetFabrique;
import patterns.abstractfactory.fabrique.a.FenetreA;
import patterns.abstractfactory.fabrique.a.ScrollBarA;
import patterns.abstractfactory.fabrique.a.WidgetFabriqueA;

class WidgetFabriqueATest {
    private WidgetFabriqueA fabriqueA = new WidgetFabriqueA();
    
    @Test void doit_EtreDeTypeWidgetFabrique(){
        assertTrue(fabriqueA instanceof WidgetFabrique );
    }

    @Test void doit_AvoirUneMethodePourCreerDesScrollbars(){
        assertNotNull(fabriqueA.fabriqueScrollBar());
    }
    
    @Test void fabriqueScrollbar_doit_RetournerDesScrollbarsDeTypeA(){
        assertTrue(fabriqueA.fabriqueScrollBar() instanceof ScrollBarA);
    }

    @Test void fabriqueScrollbar_doit_RetournerDesScrollbars(){
        assertTrue(fabriqueA.fabriqueScrollBar() instanceof ScrollBar);
    }
    
    @Test void fabriqueFenetre_doit_AvoirUneMethodePourCreerDesFenetres(){
        assertNotNull(fabriqueA.fabriqueFenetre());
    }
    
    @Test void fabriqueFenetre_doit_RetournerUneFenetreDeTypeA(){
        assertTrue(fabriqueA.fabriqueFenetre() instanceof FenetreA);
    }
    
    @Test void fabriqueFenetre_doit_RetournerUneFenetre(){
        assertTrue(fabriqueA.fabriqueFenetre() instanceof Fenetre);
    }
}
