/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package patterns.abstractfactory;

import patterns.abstractfactory.fabrique.Fenetre;
import patterns.abstractfactory.fabrique.ScrollBar;
import patterns.abstractfactory.fabrique.WidgetFabrique;
import patterns.abstractfactory.fabrique.a.WidgetFabriqueA;
import patterns.abstractfactory.fabrique.b.WidgetFabriqueB;

public class App {

    public static void main(String[] args) {
        WidgetFabrique fba = new WidgetFabriqueA();
        WidgetFabrique fbb = new WidgetFabriqueB();

        ScrollBar sa = fba.fabriqueScrollBar();
        ScrollBar sb = fbb.fabriqueScrollBar();
        
        Fenetre fa = fba.fabriqueFenetre();
        Fenetre fb = fbb.fabriqueFenetre();
    }

}
